@echo off
echo Creating kakao-mcp conda environment...
conda create -n kakao-mcp python=3.11 -y
echo Activating environment...
call conda activate kakao-mcp
echo Installing dependencies...
pip install "mcp[cli]>=1.3.0" pywin32 pyperclip watchdog pytest
echo Installing package in editable mode...
pip install -e .
echo Done! Environment 'kakao-mcp' is ready.
